export const UPDATE_LOADING_STATUS = 'UPDATE_LOADING_STATUS'
export const UPDATE_INVALID_RESPONSE = 'UPDATE_INVALID_RESPONSE'
export const SAVE_USER_INFO = 'SAVE_USER_INFO'
export const SAVE_USER_CONTACT = 'SAVE_USER_CONTACT'
